#!/usr/bin/env python3
"""Generate the STM32 message ID header from protocol/message_ids.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def render_header(manifest: dict[str, Any]) -> str:
    version = manifest["protocol_version"]
    messages = sorted(manifest["messages"], key=lambda message: message["id"])

    lines = [
        "/* Generated by tools/setup/firmware/generate_protocol_header.py; do not edit manually. */",
        "#ifndef ACTUATOR_CORE_MESSAGE_IDS_H",
        "#define ACTUATOR_CORE_MESSAGE_IDS_H",
        "",
        "#include <stdint.h>",
        "",
        "#ifndef ACTUATOR_PROTOCOL_VERSION",
        f"#define ACTUATOR_PROTOCOL_VERSION {version}u",
        "#endif",
        "",
        "typedef enum {",
    ]
    for message in messages:
        lines.append(f"    ACTUATOR_MSG_{message['name']} = {message['id']}u,")
    lines.extend(
        [
            "} actuator_message_id_t;",
            "",
            "#endif",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "manifest",
        nargs="?",
        type=Path,
        default=Path("protocol/message_ids.json"),
    )
    parser.add_argument(
        "output",
        nargs="?",
        type=Path,
        default=Path("firmware/stm32_actuator/include/actuator_core/message_ids.h"),
    )
    parser.add_argument("--check", action="store_true", help="fail if the checked-in header is stale")
    args = parser.parse_args()

    try:
        manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
        rendered = render_header(manifest)
    except (OSError, json.JSONDecodeError, KeyError, TypeError) as exc:
        print(f"[ERROR] Could not generate protocol header: {exc}")
        return 2

    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"[FAIL] Generated protocol header is missing: {exc}")
            return 1
        if current != rendered:
            print(f"[FAIL] {args.output} is stale; regenerate it.")
            return 1
        print(f"[PASS] {args.output} matches the protocol manifest.")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"[PASS] Generated {args.output}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
